title: Mehameha
baseURL: http://blog.zhizhiting.com
languageCode: zh-CN
theme: maupassant
paginate: 10
PaginatePath: "page"
enableRobotsTXT: true
enableEmoji: true
copyright: ''
author:
  name: Scott
  homepage: "http://blog.zhizhiting.com"
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
markup:
  highlight:
    lineNos: false
    style: monokailight
menu:
  main:
    - 
      identifier: archives
      name: 归档
      url: /archives/
      weight: 3
    - 
      identifier: about
      name: 关于
      url: /about/
      weight: 4

summaryLength: 140
hasCJKLanguage: true
subtitle: 专注于Java、Python、项目管理、软件架构
keywords: Java、Python、MySQL、Groovy、大数据
disablePathToLower: true
params:
  busuanzi: true
  description: 莫道君行早，更有早行人。
  toc: false
  sequenceDiagrams:
    enable: true
    options: ""
  flowchartDiagrams:
    enable: true
    options: ""
  localSearch: true
  disqusShortname: "Scott"
  cc:
    name: "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link: "https://creativecommons.org/licenses/by-nc-nd/4.0/"
