backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/post'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发布日期', name: 'date', widget: 'datetime' }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '标签', name: 'tags', widget: 'list', allow_add: true, default: ['读书']}
      - { label: '分类', name: 'categories', widget: 'list', allow_add: true, default: ['笔记']}
      - { label: '内容', name: 'body', widget: 'markdown' }
